-- Chapter 07. 01 온라인 강의 프로젝트 스키마 생성
-- 시작 상태: course_project 스키마가 존재하지 않음
-- 완료 상태: 전용 스키마·네 테이블·활성 신청 인덱스 생성, 네 테이블 0행
-- 전체 생성을 하나의 트랜잭션으로 실행합니다.

SELECT current_database();
SELECT current_user;
SELECT current_schema();
SHOW search_path;

BEGIN;

DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '스키마 생성 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF NOT has_database_privilege(current_user, current_database(), 'CREATE') THEN
        RAISE EXCEPTION
            '스키마 생성 중단: 사용자 %에게 데이터베이스 %의 CREATE 권한이 없습니다.',
            current_user,
            current_database();
    END IF;

    IF current_setting('transaction_read_only')::boolean THEN
        RAISE EXCEPTION
            '스키마 생성 중단: 현재 연결이 읽기 전용입니다.';
    END IF;

    IF to_regnamespace('course_project') IS NOT NULL THEN
        RAISE EXCEPTION
            '스키마 생성 중단: course_project 스키마가 이미 존재합니다. 현재 객체를 확인하거나 reset_course_project.sql을 검토하세요.';
    END IF;
END
$$;

CREATE SCHEMA course_project;

-- P07-R01·R07: 학생 정보와 테이블 내부 이메일 고유성
CREATE TABLE course_project.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT uq_course_students_email
        UNIQUE (email),

    CONSTRAINT chk_course_students_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    CONSTRAINT chk_course_students_email_not_blank
        CHECK (char_length(trim(email)) > 0)
);

-- P07-R02·R07: 강사 정보와 테이블 내부 이메일 고유성
CREATE TABLE course_project.instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    specialty VARCHAR(100) NOT NULL,

    CONSTRAINT uq_course_instructors_email
        UNIQUE (email),

    CONSTRAINT chk_course_instructors_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    CONSTRAINT chk_course_instructors_email_not_blank
        CHECK (char_length(trim(email)) > 0),

    CONSTRAINT chk_course_instructors_specialty_not_blank
        CHECK (char_length(trim(specialty)) > 0)
);

-- P07-R03·R04·R08·R09: 강의 현재 정보와 강사 관계
CREATE TABLE course_project.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    level VARCHAR(20) NOT NULL,
    price NUMERIC(12, 0) NOT NULL,
    opened_at DATE NOT NULL,

    CONSTRAINT fk_course_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES course_project.instructors(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_course_courses_title_not_blank
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_course_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_course_courses_price
        CHECK (price >= 0)
);

-- P07-R05·R06·R08·R09: 신청 사건과 신청 시 기록 금액
CREATE TABLE course_project.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    recorded_amount NUMERIC(12, 0) NOT NULL,

    CONSTRAINT fk_course_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES course_project.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_course_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES course_project.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_course_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_course_enrollments_recorded_amount
        CHECK (recorded_amount >= 0)
);

-- P07-D03: 신청·수강중 상태의 중복만 차단
CREATE UNIQUE INDEX uq_course_enrollments_active
ON course_project.enrollments (student_id, course_id)
WHERE status IN ('신청', '수강중');

DO $$
DECLARE
    v_named_constraint_count bigint;
    v_not_null_count bigint;
    v_student_count bigint;
    v_instructor_count bigint;
    v_course_count bigint;
    v_enrollment_count bigint;
BEGIN
    IF to_regclass('course_project.students') IS NULL
       OR to_regclass('course_project.instructors') IS NULL
       OR to_regclass('course_project.courses') IS NULL
       OR to_regclass('course_project.enrollments') IS NULL
       OR to_regclass('course_project.uq_course_enrollments_active') IS NULL THEN
        RAISE EXCEPTION
            '스키마 생성 검증 실패: 프로젝트 객체가 모두 생성되지 않았습니다.';
    END IF;

    SELECT COUNT(*) INTO v_named_constraint_count
    FROM pg_constraint
    WHERE conrelid IN (
        'course_project.students'::regclass,
        'course_project.instructors'::regclass,
        'course_project.courses'::regclass,
        'course_project.enrollments'::regclass
    )
      AND conname IN (
        'uq_course_students_email',
        'chk_course_students_name_not_blank',
        'chk_course_students_email_not_blank',
        'uq_course_instructors_email',
        'chk_course_instructors_name_not_blank',
        'chk_course_instructors_email_not_blank',
        'chk_course_instructors_specialty_not_blank',
        'fk_course_courses_instructor',
        'chk_course_courses_title_not_blank',
        'chk_course_courses_level',
        'chk_course_courses_price',
        'fk_course_enrollments_student',
        'fk_course_enrollments_course',
        'chk_course_enrollments_status',
        'chk_course_enrollments_recorded_amount'
      );

    SELECT COUNT(*) INTO v_not_null_count
    FROM information_schema.columns
    WHERE table_schema = 'course_project'
      AND table_name IN ('students', 'instructors', 'courses', 'enrollments')
      AND is_nullable = 'NO';

    SELECT COUNT(*) INTO v_student_count FROM course_project.students;
    SELECT COUNT(*) INTO v_instructor_count FROM course_project.instructors;
    SELECT COUNT(*) INTO v_course_count FROM course_project.courses;
    SELECT COUNT(*) INTO v_enrollment_count FROM course_project.enrollments;

    IF v_named_constraint_count <> 15
       OR v_not_null_count <> 20
       OR v_student_count <> 0
       OR v_instructor_count <> 0
       OR v_course_count <> 0
       OR v_enrollment_count <> 0 THEN
        RAISE EXCEPTION
            '스키마 생성 검증 실패: named_constraints=%, not_null_columns=%, rows=%/%/%/%',
            v_named_constraint_count,
            v_not_null_count,
            v_student_count,
            v_instructor_count,
            v_course_count,
            v_enrollment_count;
    END IF;

    RAISE NOTICE 'Chapter 07 course project schema creation passed';
END
$$;

COMMIT;

SELECT
    to_regclass('course_project.students') AS students_table,
    to_regclass('course_project.instructors') AS instructors_table,
    to_regclass('course_project.courses') AS courses_table,
    to_regclass('course_project.enrollments') AS enrollments_table,
    to_regclass('course_project.uq_course_enrollments_active') AS active_index;